redis:
  image: redis:3.0.6

pg-data:
  image: busybox
  volumes:
    - /var/lib/postgresql/data

pg:
  environment:
    - POSTGRES_PASSWORD:${POSTGRES_PASSWORD}
  image: postgres:9.4.5
  ports:
    - 5432:5432
  volumes_from:
    - pg-data