redis:
  image: redis:3.0.6

pg-data:
  image: busybox
  volumes:
    - /var/lib/postgresql/data

pg:
  environment:
    - POSTGRES_PASSWORD:${POSTGRES_PASSWORD}
  image: postgres:9.4.5
  ports:
    - 5432:5432
  volumes_from:
    - pg-data

mail:
  image: schickling/mailcatcher
  ports:
    - 1080:1080
    - 1025:1025

stats-data:
  image: busybox
  volumes:
    - /opt/graphite/storage:/opt/graphite/storage

graphite:
  image: hopsoft/graphite-statsd
  ports:
    - 80:80
    - 8125:8125/udp
    - 8126:8126
  volumes_from:
    - stats-data

elasticsearch:
  image: elasticsearch:latest
  command: elasticsearch -Des.network.host=0.0.0.0
  volumes_from:
    - elastic_data
  ports:
    - "9200:9200"
    - "9300:9300"

elastic_data:
  image: busybox
  volumes:
    - /usr/share/elasticsearch/data

logstash:
  image: logstash:latest
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  volumes_from:
    - config
  ports:
    - "5000:5000"
  links:
    - elasticsearch

kibana:
  image: kibana
  environment:
    - NODE_OPTIONS:"--max-old-space-size=200"
    - ELASTICSEARCH_URL:elasticsearch:9200
  volumes_from:
    - config
  ports:
    - "5601:5601"
  links:
    - elasticsearch

config:
  image: busybox
  volumes:
    - ./kibana/config/kibana.yml:/opt/kibana/config/kibana.yml
    - ./logstash/config:/etc/logstash/conf.d